import { supabase } from "@/integrations/supabase/client";

/**
 * The one place this project is allowed to lie to TypeScript about Supabase.
 *
 * ── WHY IT EXISTS ───────────────────────────────────────────────────────────
 * `src/integrations/supabase/types.ts` is generated by `supabase gen types` and
 * has not been regenerated since roughly 20260807. Everything added after that
 * — bookings, hotels, hotel_pages, hotel_members, hotel_invites, expenses,
 * payments — is invisible to it, so `supabase.from("payments")` infers every
 * row as `never` and nothing downstream type-checks. The tables are real; the
 * type definitions are stale.
 *
 * ── WHY IT IS ONE FILE AND NOT TEN ──────────────────────────────────────────
 * It used to be `type LooseClient = { from: (table: string) => any }` copied
 * into ten modules, each an independent `no-explicit-any` violation and each a
 * place someone could quietly widen the hole. One escape hatch is auditable:
 * `grep looseFrom` shows exactly which code is running untyped, and the fix for
 * all of it is a single command.
 *
 * ── HOW TO DELETE THIS FILE ─────────────────────────────────────────────────
 *   npx supabase gen types typescript --project-id <id> > src/integrations/supabase/types.ts
 * then replace `looseFrom(x)` with `supabase.from(x)` and delete this module.
 * That is the actual fix; this is the scaffolding until someone can run it.
 *
 * DO NOT reach for this for a table the generated types DO cover. Losing type
 * safety on `properties` or `profiles` buys nothing and hides real mistakes.
 */

/* eslint-disable @typescript-eslint/no-explicit-any --
   The single deliberate `any` in this codebase. PostgREST's query builder is a
   deeply chained generic whose shape depends on the table, and hand-writing a
   structural type for it would be both wrong and unmaintainable. Confined to
   this file so the lint suppression is one line in one place rather than ten
   scattered ones. */

type LooseClient = {
  from: (table: string) => any;
  rpc: (fn: string, args?: Record<string, unknown>) => Promise<{ data: unknown; error: unknown }>;
};

const loose = supabase as unknown as LooseClient;

/** A table the generated types do not know about yet. */
export const looseFrom = (table: string) => loose.from(table);

/** An RPC the generated types do not know about yet. */
export const looseRpc = (fn: string, args?: Record<string, unknown>) => loose.rpc(fn, args);
