// Originally generated by Lovable. Hand-edited for Clerk auth — see the
// accessToken callback below before regenerating this file.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Optional. Set this ONLY if you configured Clerk's classic "Supabase" JWT
// template (Option A in docs/CLERK_SETUP.md) — the value is the template name,
// normally "supabase". Leave it unset when using the native Clerk↔Supabase
// integration (Option B), which signs the ordinary session token instead.
// Asking for a template that doesn't exist makes getToken() throw, which is why
// this is opt-in rather than hardcoded.
const CLERK_JWT_TEMPLATE = import.meta.env.VITE_CLERK_SUPABASE_JWT_TEMPLATE;

declare global {
  interface Window {
    Clerk?: {
      session?: {
        getToken: (options?: { template?: string }) => Promise<string | null>;
      };
    };
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  // Clerk owns the session; Supabase just validates the JWT it issues and
  // exposes the claims to RLS through auth.jwt().
  accessToken: async () => {
    // `typeof window` guard, not a bare `window.Clerk`. supabase-js invokes
    // this callback while CONSTRUCTING the client, which happens at import
    // time — so in Node (a prerender pass, a test, any server-side render) it
    // ran before anything could catch it and logged "Failed to set initial
    // Realtime auth token: window is not defined" on every import. There is no
    // Clerk session outside a browser by definition, so the honest answer there
    // is "anonymous".
    if (typeof window === "undefined") return null;

    const session = window.Clerk?.session;
    if (!session) return null;

    try {
      const token = CLERK_JWT_TEMPLATE
        ? await session.getToken({ template: CLERK_JWT_TEMPLATE })
        : await session.getToken();

      // Must be null, not '', when there is no token — an empty string still
      // produces an `Authorization: Bearer ` header and Supabase rejects it
      // instead of treating the request as anonymous.
      return token ?? null;
    } catch (err) {
      console.error('[supabase] Could not get a Clerk token:', err);
      return null;
    }
  },
});
